name: Build sample app

on:
  workflow_call

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - name: Setup Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/apps/sample-next/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the libraries
        run: yarn build
      - name: Build the sample app
        run: yarn build:sample-app
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: sample-app
          path: ${{ github.workspace }}/apps/sample-next/out
