name: Update the preview environments
on:
  workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - name: Setup Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/apps/sample-next/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the libraries
        run: yarn build
      - name: Build the sample app
        run: yarn build:sample-app
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: sample-app
          path: ${{ github.workspace }}/apps/sample-next/out

  upload_test_environment:
    name: Upload to the test environment
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: ./.github/workflows/upload-sample-app.yml
        secrets:
          notificare_services: ${{ secrets.SAMPLE_APP_TEST_NOTIFICARE_SERVICES }}
          aws_iam_role: ${{ secrets.AWS_IAM_ROLE }}
          aws_region: ${{ secrets.AWS_REGION }}
          bucket_name: ${{ secrets.SAMPLE_APP_TEST_BUCKET_NAME }}
          distribution_id: ${{ secrets.SAMPLE_APP_TEST_DISTRIBUTION_ID }}

  upload_production_environment:
    name: Upload to the production environment
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: ./.github/workflows/upload-sample-app.yml
        secrets:
          notificare_services: ${{ secrets.SAMPLE_APP_NOTIFICARE_SERVICES }}
          aws_iam_role: ${{ secrets.AWS_IAM_ROLE }}
          aws_region: ${{ secrets.AWS_REGION }}
          bucket_name: ${{ secrets.SAMPLE_APP_BUCKET_NAME }}
          distribution_id: ${{ secrets.SAMPLE_APP_DISTRIBUTION_ID }}
