name: Update the preview environments
on:
  workflow_dispatch

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - name: Setup Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/apps/sample-next/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the libraries
        run: yarn build
      - name: Build the sample app
        run: yarn build:sample-app
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: sample-app
          path: ${{ github.workspace }}/apps/sample-next/out

  upload:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: sample-app
          path: build
      - name: Deploy to the production environment
        uses: reggionick/s3-deploy@v4
        with:
          folder: build
          bucket: ${{ secrets.SAMPLE_APP_BUCKET_NAME }}
          bucket-region: ${{ secrets.AWS_REGION }}
          delete-removed: true
          dist-id: ${{ secrets.SAMPLE_APP_DISTRIBUTION_ID }}
          invalidation: /
      - name: Deploy to the test environment
        uses: reggionick/s3-deploy@v4
        with:
          folder: build
          bucket: ${{ secrets.SAMPLE_APP_TEST_BUCKET_NAME }}
          bucket-region: ${{ secrets.AWS_REGION }}
          delete-removed: true
          dist-id: ${{ secrets.SAMPLE_APP_TEST_DISTRIBUTION_ID }}
          invalidation: /
